[package]
name = "wifi-connect"
version = "4.0.4"
authors = ["Zahari Petkov <zahari@resin.io>", "Aaron Brodersen <aaron@resin.io>"]
description = "Easy WiFi setup for Linux devices from your mobile phone or laptop"

[dependencies]
network-manager = "0.9"
clap = "2.24"
iron = "0.5"
staticfile = "0.4"
mount = "0.3"
router = "0.5"
serde_json = "1.0"
persistent = "0.3"
params = "0.6"
log = "0.3"
env_logger = "0.4"

[dependencies.error-chain]
version = "0.11"
default-features = false

[profile.release]
lto = true
