[package]
name = "resin-wifi-connect"
version = "0.1.0"
authors = ["Joe Roberts <joe@resin.io>"]
description = "Wi-Fi credentials configuration tool"

[dependencies]
clap = "2.24"
iron = "0.5"
staticfile = "0.4"
mount = "0.3"
router = "0.5"
serde_json = "1.0"
persistent = "0.3"
params = "0.6"
log = "0.3"
env_logger = "0.4"

[dependencies.network_manager]
git = "https://github.com/resin-io-modules/network_manager"
version = "0.3"

[dependencies.clippy]
version = "*"
optional = true

[profile.release]
lto = true
