[package]
name = "resin-wifi-connect"
version = "3.0.0"
authors = ["Joe Roberts <joe@resin.io>", "Zahari Petkov <zahari@resin.io>"]
description = "Wi-Fi credentials configuration tool"

[dependencies]
network-manager = "0.8"
clap = "2.24"
iron = "0.5"
staticfile = "0.4"
mount = "0.3"
router = "0.5"
serde_json = "1.0"
persistent = "0.3"
params = "0.6"
log = "0.3"
env_logger = "0.4"

[dependencies.clippy]
version = "*"
optional = true

[profile.release]
lto = true
