build: &build
  docker:
    - image: majorz/rust-$CIRCLE_JOB:rust-1.23.0

      environment:
        BINARY: wifi-connect
        TARGET_OS: linux

  steps:
    - checkout

    - run: cargo build --release --target=$TARGET

    - run: cross-strip target/$TARGET/release/$BINARY

    - run: |
        VERSION=$CIRCLE_TAG
        if [ -z "$CIRCLE_TAG" ]; then VERSION="$CIRCLE_BRANCH-$(echo $CIRCLE_SHA1 | cut -c -7)"; fi
        echo "VERSION=$VERSION"
        echo "export VERSION=$VERSION" >> $BASH_ENV

    - run: |
        ARCHIVE_NAME="$BINARY-$VERSION-$TARGET_OS-$CIRCLE_JOB.tar.gz"
        echo "ARCHIVE_NAME=$ARCHIVE_NAME"
        echo "export ARCHIVE_NAME=$ARCHIVE_NAME" >> $BASH_ENV

    - run: |
        ARCHIVE_PATH="/tmp/dist/$ARCHIVE_NAME"
        echo "ARCHIVE_PATH=$ARCHIVE_PATH"
        echo "export ARCHIVE_PATH=$ARCHIVE_PATH" >> $BASH_ENV

    - run: mkdir -p pack /tmp/dist
    - run: mv target/$TARGET/release/$BINARY pack/$BINARY
    - run: cp -R ui/build pack/ui
    - run: tar -czvf $ARCHIVE_PATH -C pack .
    - run: rm -rdf pack

    - store_artifacts:
        path: /tmp/dist
        destination: /

version: 2

jobs:
  aarch64:
    <<: *build
    environment:
      TARGET: aarch64-unknown-linux-gnu

  rpi:
    <<: *build
    environment:
      TARGET: arm-unknown-linux-gnueabihf

  armv7hf:
    <<: *build
    environment:
      TARGET: armv7-unknown-linux-gnueabihf

  i386:
    <<: *build
    environment:
      TARGET: i686-unknown-linux-gnu

  amd64:
    <<: *build
    environment:
      TARGET: x86_64-unknown-linux-gnu

  test:
    docker:
      - image: majorz/rust-test-deploy:rust-nightly-2018-01-08
    steps:
      - checkout

      - run:
          name: Get the username associated with the GitHub token
          command: |
            USER_URL=https://api.github.com/user
            GITHUB_TOKEN_USER=$(curl -s -H "Authorization: token $GITHUB_TOKEN" "$USER_URL" | jq -r .login)
            echo "GITHUB_TOKEN_USER=$GITHUB_TOKEN_USER"
            echo "export GITHUB_TOKEN_USER=$GITHUB_TOKEN_USER" >> $BASH_ENV

      - run:
          name: Test whether the username was retrieved successfully
          command: test -n "$GITHUB_TOKEN_USER" && test "$GITHUB_TOKEN_USER" != null

      - run:
          name: Get the repository permissions for the GitHub token
          command: |
            PERM_URL="https://api.github.com/repos/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/collaborators/$GITHUB_TOKEN_USER/permission"
            GITHUB_TOKEN_PERM=$(curl -s -H "Authorization: token $GITHUB_TOKEN" "$PERM_URL" | jq -r .permission)
            echo "GITHUB_TOKEN_PERM=$GITHUB_TOKEN_PERM"
            echo "export GITHUB_TOKEN_PERM=$GITHUB_TOKEN_PERM" >> $BASH_ENV

      - run:
          name: Test whether the permissions are `write` or `admin`
          command: test -n "$GITHUB_TOKEN_PERM" && (test "$GITHUB_TOKEN_PERM" = write || test "$GITHUB_TOKEN_PERM" = admin)

      - run: cargo fmt -- --write-mode=diff
      - run: cargo clippy -- -D warnings

  deploy:
    docker:
      - image: majorz/rust-test-deploy:rust-nightly-2018-01-08

    steps:
      - checkout

      - deploy:
          command: ./scripts/deploy.sh

workflows:
  version: 2
  build:
    jobs:
      - test:
          filters:
            branches:
              only: /.*/
            tags:
              only: /.*/
      - aarch64:
          requires:
            - test
          filters:
            branches:
              only: /.*/
            tags:
              only: /.*/
      - rpi:
          requires:
            - test
          filters:
            branches:
              only: /.*/
            tags:
              only: /.*/
      - armv7hf:
          requires:
            - test
          filters:
            branches:
              only: /.*/
            tags:
              only: /.*/
      - i386:
          requires:
            - test
          filters:
            branches:
              only: /.*/
            tags:
              only: /.*/
      - amd64:
          requires:
            - test
          filters:
            branches:
              only: /.*/
            tags:
              only: /.*/
      - deploy:
          requires:
            - aarch64
            - rpi
            - armv7hf
            - i386
            - amd64
          filters:
            branches:
              only: /.*/
            tags:
              only: /.*/
