build: &build
  docker:
    - image: majorz/rust-$CIRCLE_JOB:rust-1.23.0

      environment:
        BINARY: wifi-connect
        TARGET_OS: linux

  steps:
    - checkout

    - run: cargo build --release --target=$TARGET
 
    - run: cross-strip target/$TARGET/release/$BINARY

    - run: |
        VERSION=$CIRCLE_TAG
        if [ -z "$CIRCLE_TAG" ]; then VERSION="$CIRCLE_BRANCH-$(echo $CIRCLE_SHA1 | cut -c -7)"; fi
        echo "VERSION=$VERSION"
        echo "export VERSION=$VERSION" >> $BASH_ENV

    - run: |
        ARCHIVE_NAME="$BINARY-$VERSION-$TARGET_OS-$CIRCLE_JOB.tar.gz"
        echo "ARCHIVE_NAME=$ARCHIVE_NAME"
        echo "export ARCHIVE_NAME=$ARCHIVE_NAME" >> $BASH_ENV

    - run: |
        ARCHIVE_PATH="/tmp/dist/$ARCHIVE_NAME"
        echo "ARCHIVE_PATH=$ARCHIVE_PATH"
        echo "export ARCHIVE_PATH=$ARCHIVE_PATH" >> $BASH_ENV

    - run: mkdir -p pack /tmp/dist
    - run: mv target/$TARGET/release/$BINARY pack/$BINARY
    - run: cp -R ui pack/ui
    - run: tar -czvf $ARCHIVE_PATH -C pack .
    - run: rm -rdf pack

    - store_artifacts:
        path: /tmp/dist
        destination: /

version: 2

jobs:
  aarch64:
    <<: *build
    environment:
      TARGET: aarch64-unknown-linux-gnu

  rpi:
    <<: *build
    environment:
      TARGET: arm-unknown-linux-gnueabihf

  armv7hf:
    <<: *build
    environment:
      TARGET: armv7-unknown-linux-gnueabihf

  i386:
    <<: *build
    environment:
      TARGET: i686-unknown-linux-gnu

  amd64:
    <<: *build
    environment:
      TARGET: x86_64-unknown-linux-gnu

  test:
    docker:
      - image: majorz/rust-test-deploy:rust-nightly-2018-01-08
    steps:
      - checkout

      - run: cargo fmt -- --write-mode=diff
      - run: cargo clippy -- -D warnings

  deploy:
    docker:
      - image: majorz/rust-test-deploy:rust-nightly-2018-01-08

    environment:
      GITHUB_USER: resin-io
      GITHUB_REPO: resin-wifi-connect

    steps:
      - checkout

      - deploy:
          command: ./scripts/deploy.sh

workflows:
  version: 2
  build:
    jobs:
      - test:
          filters:
            branches:
              only: /.*/
            tags:
              only: /.*/
      - aarch64:
          requires:
            - test
          filters:
            branches:
              only: /.*/
            tags:
              only: /.*/
      - rpi:
          requires:
            - test
          filters:
            branches:
              only: /.*/
            tags:
              only: /.*/
      - armv7hf:
          requires:
            - test
          filters:
            branches:
              only: /.*/
            tags:
              only: /.*/
      - i386:
          requires:
            - test
          filters:
            branches:
              only: /.*/
            tags:
              only: /.*/
      - amd64:
          requires:
            - test
          filters:
            branches:
              only: /.*/
            tags:
              only: /.*/
      - deploy:
          requires:
            - aarch64
            - rpi
            - armv7hf
            - i386
            - amd64
          filters:
            branches:
              only: /.*/
            tags:
              only: /.*/
